name: app_auto_updater
description: "A new Flutter project."
 
publish_to: 'none' 
 
version: 1.0.7

environment:
  sdk: '>=3.4.4 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  auto_updater: ^0.2.1
  window_manager: ^0.4.2
  bot_toast: ^4.1.3
  preference_list: ^0.0.2
  flutter_sparkle: ^0.0.2
  flutter_distributor: ^0.4.5
  package_info_plus: ^8.0.3
  flutter_launcher_icons: ^0.14.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.0
 
flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
 
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/cheque_icon.png"
    icon_size: 48 # min:48, max:256, default: 48